// sacred-history.ts — typed loader for the sacred-history corpus web data.
//
// Source of truth: src/data/sacred-history.json, generated by
// _intake/sacred-history-corpus/tools/build-web-data.py from the local
// (ollama-only) pipeline outputs. Tier-A (public-domain / open / CC0) only.

import data from "@/data/sacred-history.json";

export type SHFigure = {
  id: string;
  label: string;
  aka: string[];
  traditions: string[];
  figureClass: string | null;
  historicity: string | null;
  motifs: string[];
  wikidata: string | null;
  wikidataUrl: string | null;
};

export type SHEvidence = {
  kind: string | null;
  locator: string | null;
  sourceNode: string | null;
  rightsTier: string | null;
  summary: string | null;
};

export type SHSide = {
  tradition: string | null;
  node: string | null;
  wikidata: string | null;
};

export type SHCorrelation = {
  id: string;
  kind: string;
  label: string | null;
  statement: string | null;
  sideA: SHSide;
  sideB: SHSide;
  stance: string;
  disputed: boolean;
  confidence: number | null;
  scope: string | null;
  evidence: SHEvidence[];
  counterConsiderations: string[];
  provenance: {
    assertedBy: string | null;
    method: string | null;
    model: string | null;
    runId: string | null;
    addedOn: string | null;
  };
  source: string;
};

export type SHEvent = {
  id: string;
  label: string;
  eventClass: string;
  traditions: string[];
  year: number;
  precision: string | null;
  disputed: boolean;
  wikidata: string | null;
  wikidataUrl: string | null;
  note: string | null;
  layer: string;
};

export type SacredHistory = {
  generatedAt: string;
  title: string;
  tagline: string;
  summary: {
    figures: number;
    traditions: number;
    correlations: number;
    timelineEvents: number;
    earliestEvent: string | null;
    latestEvent: string | null;
  };
  rights: { tier: string; policy: string };
  method: string;
  traditions: string[];
  figures: SHFigure[];
  correlations: SHCorrelation[];
  timeline: SHEvent[];
};

const SH = data as unknown as SacredHistory;

export function getSacredHistory(): SacredHistory {
  return SH;
}

export function yearLabel(year: number): string {
  return `${Math.abs(year)} ${year < 0 ? "BCE" : "CE"}`;
}

// Human-readable tradition labels (the data uses lowercase slugs).
const TRADITION_LABELS: Record<string, string> = {
  judaism: "Judaism",
  christianity: "Christianity",
  islam: "Islam",
  hinduism: "Hinduism",
  buddhism: "Buddhism",
  jainism: "Jainism",
  sikhism: "Sikhism",
  bahai: "Bahá'í",
  lds: "Latter Day Saint",
  zoroastrianism: "Zoroastrianism",
  "tao-confucian": "Tao / Confucian",
  greek: "Greek",
  mesopotamian: "Mesopotamian",
  cross: "Cross-tradition",
};

export function traditionLabel(slug: string): string {
  return TRADITION_LABELS[slug] ?? slug.replace(/-/g, " ");
}
