import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { chromium } from "playwright";
import script from "./chapters.json";

const bin = resolve(process.argv[2] || "../../.local/bin/bucket");
const versionResult = Bun.spawnSync([bin, "--version"], { stdout: "pipe", stderr: "pipe" });
const version = versionResult.stdout.toString().trim();
if (versionResult.exitCode || version !== script.version) throw new Error(`Expected Bucket ${script.version}, received ${version}`);
const hashResult = Bun.spawnSync(["sha256sum", bin], { stdout: "pipe", stderr: "pipe" });
if (hashResult.exitCode) throw new Error("Could not hash the desktop executable");
const binarySha256 = hashResult.stdout.toString().split(" ")[0];
const out = resolve(process.argv[3] || `.local/demo-renders/${new Date().toISOString().replaceAll(":", "-")}`);
mkdirSync(out, { recursive: true });
const runtime = join(out, "runtime");
mkdirSync(runtime, { mode: 0o700 });
const env = { ...process.env, BKT_HOME: join(out, "sample-data"), XDG_RUNTIME_DIR: runtime, BKT_KEYRING: "passphrase" };
const pass = new TextEncoder().encode("bucket-public-demo-sample-only\n");
const init = Bun.spawnSync([bin, "init", "--keyring", "passphrase", "--passphrase-fd", "0"], { env, stdin: pass, stdout: "pipe", stderr: "pipe" });
if (init.exitCode) throw new Error(init.stderr.toString());
const serve = Bun.spawn([bin, "serve", "--passphrase-fd", "0"], { env, stdin: pass, stdout: "pipe", stderr: "inherit" });
const reader = serve.stdout.getReader();
let output = "";
let url = "";
const timeout = setTimeout(() => serve.kill(), 30000);
while (!url) {
  const next = await reader.read();
  if (next.done) throw new Error(`Desktop server exited: ${output}`);
  output += new TextDecoder().decode(next.value);
  url = output.match(/http:\/\/127\.0\.0\.1:\d+\//)?.[0] || "";
}
clearTimeout(timeout);
const browser = await chromium.launch({ args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const context = await browser.newContext({ viewport: { width: 1280, height: 720 }, recordVideo: { dir: out, size: { width: 1280, height: 720 } } });
const page = await context.newPage();
const started = Date.now();
const scenes: { id: string; start: number; end?: number; text: string }[] = [];
const problems: string[] = [];
page.on("pageerror", (error) => problems.push(error.message));
async function chapter(id: string) {
  const text = script.chapters.find((entry) => entry.id === id)!.text;
  if (scenes.length) scenes.at(-1)!.end = (Date.now() - started) / 1000;
  scenes.push({ id, start: (Date.now() - started) / 1000, text });
  await page.screenshot({ path: join(out, `${id}.png`) });
}
try {
  await page.goto(url);
  await page.locator('nav a[href="#/explore"]').waitFor();
  await page.locator('nav a[href="#/explore"]').click();
  await page.locator('[data-testid="explore-query"]').waitFor();
  await page.waitForTimeout(1500);
  await chapter("explore");
  await page.locator('[data-testid="explore-query"]').fill("");
  await page.locator('[data-testid="explore-query"]').pressSequentially("mathematical theory of communication", { delay: 65 });
  await page.locator('[data-testid="explore-query"]').press("Enter");
  await page.getByTestId("explore-result").filter({ hasText: "A Mathematical Theory of Communication" }).first().waitFor({ timeout: 45000 });
  await page.getByTestId("explore-result").filter({ hasText: "A Mathematical Theory of Communication" }).first().locator("button").first().click();
  await page.getByTestId("explore-panel").getByTestId("save-button").waitFor();
  await page.locator('[data-testid="save-button"]').first().scrollIntoViewIfNeeded();
  await page.waitForTimeout(3500);
  await chapter("save");
  await page.locator('[data-testid="save-button"]').first().click();
  await page.waitForTimeout(2500);
  await page.locator('nav a[href="#/canon"]').click();
  await page.waitForTimeout(1200);
  await page.locator('nav a[href="#/explore"]').click();
  await page.locator('[data-testid="saved-panel"]').scrollIntoViewIfNeeded();
  if (!await page.locator('[data-testid="saved-panel"] li').count()) throw new Error("Saved result missing");
  await page.waitForTimeout(3500);
  await page.evaluate(() => { window.location.hash = "#/search"; });
  await page.getByRole("searchbox", { name: "Search the canon" }).waitFor();
  await chapter("canon");
  await page.getByRole("searchbox", { name: "Search the canon" }).fill("");
  await page.getByRole("searchbox", { name: "Search the canon" }).pressSequentially("entropy", { delay: 160 });
  await page.getByRole("searchbox", { name: "Search the canon" }).press("Enter");
  await page.locator("a.hit").first().waitFor();
  await page.waitForTimeout(5000);
  await page.locator('nav a[href="#/learn"]').click();
  await page.waitForTimeout(1000);
  await chapter("learn");
  await page.waitForTimeout(6000);
  await page.locator('nav a[href="#/notes"]').click();
  await page.getByRole("button", { name: "New note" }).click();
  await page.getByRole("textbox", { name: "Title", exact: true }).fill("A coin, a question, a bit");
  await page.locator("textarea.body-input").fill("# What makes a coin uncertain?\n\nA fair coin has two equally likely outcomes. Its binary entropy is one bit.\n\nSource: Claude Shannon, A Mathematical Theory of Communication (1948).\nhttps://doi.org/10.1002/j.1538-7305.1948.tb00917.x\n\nNext question: what changes when the coin is biased?");
  await page.waitForTimeout(1500);
  await chapter("notes");
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await page.waitForTimeout(6500);
  await page.locator('nav a[href="#/jobs"]').click();
  await page.waitForTimeout(1000);
  await chapter("data");
  await page.waitForTimeout(6000);
  await page.locator('a[href="#/add"]').click();
  await page.waitForTimeout(1000);
  await chapter("add");
  await page.waitForTimeout(6000);
  scenes.at(-1)!.end = (Date.now() - started) / 1000;
  if (problems.length) throw new Error(JSON.stringify(problems));
} catch (error) {
  problems.push(String(error));
  await page.screenshot({ path: join(out, "failure.png") });
  throw error;
} finally {
  await context.close();
  writeFileSync(join(out, "capture.json"), JSON.stringify({ version, binarySha256, video: await page.video()!.path(), scenes, problems }, null, 2));
  await browser.close();
  serve.kill();
  await serve.exited;
}
console.log(out);
