/* Bucket Academy — public Supabase config for optional sign-in (bkt-su9).
 *
 * This file is REGENERATED by scripts/sync-academy.mjs at build time from the
 * public env vars NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.
 * The anon key is public by design — Row-Level Security is the real boundary.
 *
 * The committed default below is EMPTY, which keeps auth disabled so the app
 * runs purely anonymous + local-first (e.g. via ./serve.sh) with no backend.
 * Never put a SERVICE ROLE key here.
 */
window.__BUCKET_SUPABASE = { url: "", anonKey: "" };
