import { cpSync, rmSync, mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "learning", "app");
const dest = join(root, "public", "academy-app");
const EXCLUDE = new Set([
  "serve.sh", "validate.sh", "README.md", "vercel.json", "node_modules", ".vercel",
  "test-adaptive.js",
  "test-diagnostic.mjs", "test-headless-flow.mjs",
  "test-assess.mjs", "test-assess-flow.mjs",
  "test-explorer.mjs",
  "test-lang-flow.mjs",
  "build-art.mjs", "build-icons.mjs", "icon-maskable.svg",
  "_build",
]);

if (!existsSync(src)) {
  console.error("[sync-academy] source not found:", src);
  process.exit(0);
}
rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });
cpSync(src, dest, {
  recursive: true,
  filter: (s) => !EXCLUDE.has(s.split("/").pop()),
});
console.log("[sync-academy] copied learning/app → public/academy-app");

function readEnvFiles() {
  const out = {};
  for (const f of [".env.local", ".env"]) {
    const p = join(root, f);
    if (!existsSync(p)) continue;
    for (const line of readFileSync(p, "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let v = m[2].trim();
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'")))
        v = v.slice(1, -1);
      if (out[m[1]] === undefined) out[m[1]] = v;
    }
  }
  return out;
}

const envFiles = readEnvFiles();
const url = process.env.NEXT_PUBLIC_SUPABASE_URL || envFiles.NEXT_PUBLIC_SUPABASE_URL || "";
const anonKey =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || envFiles.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

const configJs =
  "/* Bucket Academy — public Supabase config (GENERATED by scripts/sync-academy.mjs).\n" +
  " * The anon key is public by design; Row-Level Security is the real boundary.\n" +
  " * When empty, the Academy's optional sign-in disables itself (anonymous + local-first). */\n" +
  "window.__BUCKET_SUPABASE = " +
  JSON.stringify({ url, anonKey }) +
  ";\n";
writeFileSync(join(dest, "js", "auth-config.js"), configJs);
console.log(
  "[sync-academy] auth-config.js " +
    (url && anonKey ? "wired (sign-in ENABLED)" : "empty (sign-in disabled — set NEXT_PUBLIC_SUPABASE_* to enable)")
);
