/* Sync the Bucket Academy app (source of truth: learning/app) into public/academy-app
 * so the Next.js site serves it at /academy-app and the /academy route can frame it.
 * Runs automatically via the predev/prebuild npm hooks, and can be run by hand.
 * Excludes dev-only files (serve.sh, validate.sh, README, vercel.json, node_modules). */
import { cpSync, rmSync, mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "learning", "app");
const dest = join(root, "public", "academy-app");
const EXCLUDE = new Set([
  "serve.sh", "validate.sh", "README.md", "vercel.json", "node_modules", ".vercel",
  "test-adaptive.js", // dev-only engine test (bkt-jh0); never ship to /academy-app
  "test-diagnostic.mjs", "test-headless-flow.mjs", // dev-only diagnostic tests (bkt-efk)
  "test-assess.mjs", "test-assess-flow.mjs", // dev-only assessment tests (bkt-v7y / bkt-3so)
  "test-explorer.mjs", // dev-only Polingual explorer smoke test (bkt-nhy)
  // build-time art/icon generators are dev-only; the committed cache + PNGs ship instead
  "build-art.mjs", "build-icons.mjs", "icon-maskable.svg",
]);

if (!existsSync(src)) {
  console.error("[sync-academy] source not found:", src);
  process.exit(0); // don't break the build if the app folder isn't present
}
rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });
cpSync(src, dest, {
  recursive: true,
  filter: (s) => !EXCLUDE.has(s.split("/").pop()),
});
console.log("[sync-academy] copied learning/app → public/academy-app");

/* Inject PUBLIC Supabase config for the Academy's optional sign-in (bkt-su9).
 * Both values are public by design (the anon key is meant to ship to browsers;
 * Row-Level Security is the real boundary). We read process.env first, then
 * fall back to parsing .env.local / .env so the prebuild hook works even when
 * it runs before Next loads its env. When both are absent, we write an EMPTY
 * config → auth disables itself and the app stays anonymous + local-first. */
function readEnvFiles() {
  const out = {};
  for (const f of [".env.local", ".env"]) {
    const p = join(root, f);
    if (!existsSync(p)) continue;
    for (const line of readFileSync(p, "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let v = m[2].trim();
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'")))
        v = v.slice(1, -1);
      if (out[m[1]] === undefined) out[m[1]] = v; // first file wins (.env.local > .env)
    }
  }
  return out;
}

const envFiles = readEnvFiles();
const url = process.env.NEXT_PUBLIC_SUPABASE_URL || envFiles.NEXT_PUBLIC_SUPABASE_URL || "";
const anonKey =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || envFiles.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

const configJs =
  "/* Bucket Academy — public Supabase config (GENERATED by scripts/sync-academy.mjs).\n" +
  " * The anon key is public by design; Row-Level Security is the real boundary.\n" +
  " * When empty, the Academy's optional sign-in disables itself (anonymous + local-first). */\n" +
  "window.__BUCKET_SUPABASE = " +
  JSON.stringify({ url, anonKey }) +
  ";\n";
writeFileSync(join(dest, "js", "auth-config.js"), configJs);
console.log(
  "[sync-academy] auth-config.js " +
    (url && anonKey ? "wired (sign-in ENABLED)" : "empty (sign-in disabled — set NEXT_PUBLIC_SUPABASE_* to enable)")
);
