import * as fs from "fs";
import * as path from "path";
import { detectFormat, genomeOffset, GENOME_LENGTH, parseFasta, summarize } from "../src/lib/explore/genome/parse";
import { dnaMode, genesCited, slotOf, DNA_SLOTS } from "../src/lib/explore/modes/dna";
import { MAX_GENOME_BYTES, ParseTokens, runGenomeJob, sizeError } from "../src/lib/explore/genome/job";
import { HELIX_RADIUS } from "../src/lib/explore/modes/helix";
import { SAMPLE_HITS } from "./lib/explore-hits";

let failed = 0;
function check(name: string, cond: boolean, detail = "") {
  console.log(`${cond ? "PASS" : "FAIL"}  ${name}${detail ? ` :: ${detail}` : ""}`);
  if (!cond) failed++;
}

const t23 = "# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\nrs1801133\t1\t11856378\tAG\ni700001\t2\t5000\tCC\nrs429358\t19\t45411941\tTT\n";
const anc = "#AncestryDNA raw data download\nrsid\tchromosome\tposition\tallele1\tallele2\nrs4680\t22\t19951271\tA\tG\nrs1\t23\t100\tT\tT\n";
const vcf = "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\nchr16\t53820527\trs9939609\tT\tA\t.\tPASS\t.\tGT\t0/1\nchrM\t100\t.\tA\tG,C\t.\tPASS\t.\tGT:DP\t2|2:10\n";
const fa = ">seq1 test\nACGTGC\nNN\n>seq2\nAAAA\n";

check("detects 23andMe", detectFormat(t23) === "23andme");
check("detects AncestryDNA", detectFormat(anc) === "ancestry");
check("detects VCF", detectFormat(vcf) === "vcf");
check("detects FASTA", detectFormat(fa) === "fasta");
check("unknown text stays unknown", detectFormat("hello world") === "unknown");

const s23 = summarize(t23);
check("23andMe variant count", s23.variantCount === 3);
check("23andMe annotates MTHFR and APOE", s23.annotated.map((a) => a.gene).sort().join() === "APOE,MTHFR");
check("23andMe keeps genotype", s23.annotated.find((a) => a.gene === "MTHFR")?.genotype === "AG");

const sAnc = summarize(anc);
check("Ancestry joins alleles", sAnc.annotated[0]?.genotype === "AG" && sAnc.annotated[0]?.gene === "COMT");
check("Ancestry maps chromosome 23 to X", sAnc.perChrom.X === 1);

const sVcf = summarize(vcf);
check("VCF reads GT", sVcf.annotated[0]?.gene === "FTO" && sVcf.annotated[0]?.genotype === "TA");
check("VCF maps chrM and multi-allelic GT", sVcf.perChrom.MT === 1 && sVcf.markers.some((m) => m.genotype === "CC"));

const recs = parseFasta(fa);
check("FASTA records", recs.length === 2 && recs[0].length === 8 && recs[1].length === 4);
check("FASTA GC fraction", Math.abs(recs[0].gc - 4 / 8) < 1e-9);

check("genome offset is monotone across chromosomes", genomeOffset("2", 0) > genomeOffset("1", 1) && genomeOffset("MT", 0) < GENOME_LENGTH);
check("slots span the helix", slotOf("1", 0) === 0 && slotOf("MT", 16569) <= DNA_SLOTS - 1 + 1e-9);

const sample = fs.readFileSync(path.join(__dirname, "../public/explore/sample-genome.txt"), "utf8");
const sSample = summarize(sample);
check("bundled sample parses as 23andMe", sSample.format === "23andme" && sSample.variantCount > 200);
check("bundled sample carries every annotated SNP", sSample.annotated.length === 14);

check("gene citation needs a whole word", genesCited(SAMPLE_HITS[0], ["MTHFR", "LCT"]).join() === "MTHFR");

const empty = dnaMode.layout([], { selected: null, scroll: 0 });
check("reference layout shows the bundled SNPs", empty.nodes.filter((n) => n.id.startsWith("snp:")).length === 14);
const loaded = dnaMode.layout(SAMPLE_HITS, { selected: null, scroll: 0, genome: s23 });
check("loaded layout shows the file's annotated SNPs", loaded.nodes.filter((n) => n.id.startsWith("snp:")).length === 2);
check("loaded layout draws markers", loaded.nodes.some((n) => n.id.startsWith("marker:")));
check("excerpt citing MTHFR links to its SNP", loaded.links.some((l) => l.from === SAMPLE_HITS[0].id && l.to === "snp:rs1801133"));
check("positions are finite", loaded.nodes.every((n) => n.position.every(Number.isFinite)));

check("markers ride the outer strand", loaded.nodes.filter((n) => n.id.startsWith("marker:")).every((n) => Math.abs(Math.hypot(n.position[0], n.position[2]) - HELIX_RADIUS) < 1e-9));
check("SNPs ride the inner strand", loaded.nodes.filter((n) => n.id.startsWith("snp:")).every((n) => Math.abs(Math.hypot(n.position[0], n.position[2]) - 0.92) < 1e-9));
check("citing excerpt sits outside the helix", (() => {
  const n = loaded.nodes.find((x) => x.id === SAMPLE_HITS[0].id);
  return !!n && Math.abs(Math.hypot(n.position[0], n.position[2]) - 1.6) < 1e-9;
})());
check("non-citing hits are left off the DNA view", !loaded.nodes.some((n) => n.id === SAMPLE_HITS[2].id));
check("DNA node ids are unique", new Set(loaded.nodes.map((n) => n.id)).size === loaded.nodes.length);
check("DNA links join known nodes", (() => {
  const ids = new Set(loaded.nodes.map((n) => n.id));
  return loaded.links.every((l) => ids.has(l.from) && ids.has(l.to));
})());
check("legend switches to your file once loaded", loaded.legend.some((l) => l.label === "annotated SNP in your file") && empty.legend.some((l) => l.label === "annotated SNP, reference"));
check("extra hits join the DNA layout", dnaMode.layout([], { selected: null, scroll: 0, extraHits: [SAMPLE_HITS[0]] }).nodes.some((n) => n.id === SAMPLE_HITS[0].id));
const scrolled = dnaMode.layout([], { selected: null, scroll: 400 });
check("scroll moves the DNA helix", scrolled.nodes[0].position[1] !== empty.nodes[0].position[1]);

check("size cap is 100 MB", MAX_GENOME_BYTES === 100 * 1024 * 1024);
check("files at the cap pass", sizeError(MAX_GENOME_BYTES) === null);
check("files over the cap name the limit", /100 MB/.test(sizeError(MAX_GENOME_BYTES + 1) ?? ""));

async function asyncChecks() {
  let read = false;
  const huge = { size: MAX_GENOME_BYTES + 1, text: async () => { read = true; return ""; } };
  const r = await runGenomeJob({ token: 7, file: huge });
  check("oversize file is refused before it is read", !r.ok && !read && r.token === 7);
  const ok = await runGenomeJob({ token: 8, file: { size: t23.length, text: async () => t23 } });
  check("small file parses and echoes its token", ok.ok && ok.token === 8 && ok.summary.variantCount === 3);
  const bad = await runGenomeJob({ token: 9, file: { size: 10, text: async () => { throw new Error("read failed"); } } });
  check("read errors come back as messages", !bad.ok && bad.error === "read failed");

  const tokens = new ParseTokens();
  const first = tokens.next();
  check("a fresh token is current", tokens.isCurrent(first));
  tokens.cancel();
  check("clear makes an in-flight parse stale", !tokens.isCurrent(first));
  const second = tokens.next();
  check("a newer parse supersedes an older one", tokens.isCurrent(second) && !tokens.isCurrent(first));
}

asyncChecks().then(
  () => {
    if (failed) {
      console.error(`${failed} failed`);
      process.exit(1);
    }
    console.log("all passed");
  },
  (err) => {
    console.error(err);
    process.exit(1);
  },
);
