import * as fs from "fs";
import * as path from "path";
import { detectFormat, genomeOffset, GENOME_LENGTH, parseFasta, summarize } from "../src/lib/explore/genome/parse";
import { dnaMode, genesCited, slotOf, DNA_SLOTS } from "../src/lib/explore/modes/dna";
import { SAMPLE_HITS } from "./lib/explore-hits";

let failed = 0;
function check(name: string, cond: boolean, detail = "") {
  console.log(`${cond ? "PASS" : "FAIL"}  ${name}${detail ? ` :: ${detail}` : ""}`);
  if (!cond) failed++;
}

const t23 = "# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\nrs1801133\t1\t11856378\tAG\ni700001\t2\t5000\tCC\nrs429358\t19\t45411941\tTT\n";
const anc = "#AncestryDNA raw data download\nrsid\tchromosome\tposition\tallele1\tallele2\nrs4680\t22\t19951271\tA\tG\nrs1\t23\t100\tT\tT\n";
const vcf = "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\nchr16\t53820527\trs9939609\tT\tA\t.\tPASS\t.\tGT\t0/1\nchrM\t100\t.\tA\tG,C\t.\tPASS\t.\tGT:DP\t2|2:10\n";
const fa = ">seq1 test\nACGTGC\nNN\n>seq2\nAAAA\n";

check("detects 23andMe", detectFormat(t23) === "23andme");
check("detects AncestryDNA", detectFormat(anc) === "ancestry");
check("detects VCF", detectFormat(vcf) === "vcf");
check("detects FASTA", detectFormat(fa) === "fasta");
check("unknown text stays unknown", detectFormat("hello world") === "unknown");

const s23 = summarize(t23);
check("23andMe variant count", s23.variantCount === 3);
check("23andMe annotates MTHFR and APOE", s23.annotated.map((a) => a.gene).sort().join() === "APOE,MTHFR");
check("23andMe keeps genotype", s23.annotated.find((a) => a.gene === "MTHFR")?.genotype === "AG");

const sAnc = summarize(anc);
check("Ancestry joins alleles", sAnc.annotated[0]?.genotype === "AG" && sAnc.annotated[0]?.gene === "COMT");
check("Ancestry maps chromosome 23 to X", sAnc.perChrom.X === 1);

const sVcf = summarize(vcf);
check("VCF reads GT", sVcf.annotated[0]?.gene === "FTO" && sVcf.annotated[0]?.genotype === "TA");
check("VCF maps chrM and multi-allelic GT", sVcf.perChrom.MT === 1 && sVcf.markers.some((m) => m.genotype === "CC"));

const recs = parseFasta(fa);
check("FASTA records", recs.length === 2 && recs[0].length === 8 && recs[1].length === 4);
check("FASTA GC fraction", Math.abs(recs[0].gc - 4 / 8) < 1e-9);

check("genome offset is monotone across chromosomes", genomeOffset("2", 0) > genomeOffset("1", 1) && genomeOffset("MT", 0) < GENOME_LENGTH);
check("slots span the helix", slotOf("1", 0) === 0 && slotOf("MT", 16569) <= DNA_SLOTS - 1 + 1e-9);

const sample = fs.readFileSync(path.join(__dirname, "../public/explore/sample-genome.txt"), "utf8");
const sSample = summarize(sample);
check("bundled sample parses as 23andMe", sSample.format === "23andme" && sSample.variantCount > 200);
check("bundled sample carries every annotated SNP", sSample.annotated.length === 14);

check("gene citation needs a whole word", genesCited(SAMPLE_HITS[0], ["MTHFR", "LCT"]).join() === "MTHFR");

const empty = dnaMode.layout([], { selected: null, scroll: 0 });
check("reference layout shows the bundled SNPs", empty.nodes.filter((n) => n.id.startsWith("snp:")).length === 14);
const loaded = dnaMode.layout(SAMPLE_HITS, { selected: null, scroll: 0, genome: s23 });
check("loaded layout shows the file's annotated SNPs", loaded.nodes.filter((n) => n.id.startsWith("snp:")).length === 2);
check("loaded layout draws markers", loaded.nodes.some((n) => n.id.startsWith("marker:")));
check("excerpt citing MTHFR links to its SNP", loaded.links.some((l) => l.from === SAMPLE_HITS[0].id && l.to === "snp:rs1801133"));
check("positions are finite", loaded.nodes.every((n) => n.position.every(Number.isFinite)));

if (failed) {
  console.error(`${failed} failed`);
  process.exit(1);
}
console.log("all passed");
