import { appendFileSync, copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { cpus, loadavg } from "node:os";
import { join, resolve } from "node:path";

const spike = resolve(import.meta.dir, "..");
const label = process.argv[2] ?? `${process.platform}-${process.arch}`;
const writerSeconds = process.argv[3] ?? "60";
const data = join(spike, ".data", "ci");
const exe = process.platform === "win32" ? ".exe" : "";
const bin = (profile: string, name: string) => join(spike, "target", profile, `${name}${exe}`);
rmSync(data, { recursive: true, force: true });
mkdirSync(data, { recursive: true });

type Step = { name: string; ok: boolean; seconds: number; detail?: unknown };
const steps: Step[] = [];
const result: Record<string, unknown> = { label, target: `${process.platform}-${process.arch}`, cpus: cpus().length, bun: Bun.version };

function sh(cmd: string[], cwd = spike, env: Record<string, string> = {}) {
  const t = Bun.nanoseconds();
  const p = Bun.spawnSync(cmd, { cwd, stdout: "pipe", stderr: "pipe", env: { ...process.env, ...env } });
  return { ok: p.exitCode === 0, seconds: Math.round((Bun.nanoseconds() - t) / 1e7) / 100, out: p.stdout.toString(), err: p.stderr.toString() };
}

function step(name: string, fn: () => { ok: boolean; seconds: number; detail?: unknown }) {
  let s: Step;
  try {
    s = { name, ...fn() };
  } catch (e) {
    s = { name, ok: false, seconds: 0, detail: String(e) };
  }
  steps.push(s);
  console.log(`${s.ok ? "ok  " : "FAIL"} ${name} ${s.seconds}s ${s.detail === undefined ? "" : JSON.stringify(s.detail).slice(0, 2000)}`);
  return s;
}

const lastJson = (text: string) => JSON.parse(text.trim().split("\n").filter((l) => l.startsWith("{")).pop() ?? "null");
const tail = (r: { out: string; err: string }) => (r.err || r.out).trim().split("\n").slice(-12).join("\n");

result.rustc = sh(["rustc", "--version"]).out.trim();

step("engine release build, cold", () => {
  const r = sh(["cargo", "build", "--release", "--locked", "-p", "s4-native-engine"]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? { bytes: statSync(bin("release", "engine-min")).size } : tail(r) };
});
step("engine size-optimised build", () => {
  const r = sh(["cargo", "build", "--profile", "small", "--locked", "-p", "s4-native-engine"]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? { bytes: statSync(bin("small", "engine-min")).size } : tail(r) };
});
step("engine start, --version", () => {
  const r = sh(["bun", "bench.mts", "20", "3", "--", bin("release", "engine-min"), "--version"]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? lastJson(r.out) : tail(r) };
});
step("engine opens SQLite and ranks, self-test", () => {
  const r = sh([bin("release", "engine-min"), "--selftest"]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? lastJson(r.out) : tail(r) };
});
step("other spike binaries build", () => {
  const a = sh(["cargo", "build", "--release", "--locked", "-p", "s1-two-writers", "-p", "s6-sealed-reader"]);
  const b = sh(["cargo", "build", "--profile", "parity", "--locked", "-p", "s2-ranking-parity"]);
  return { ok: a.ok && b.ok, seconds: a.seconds + b.seconds, detail: a.ok && b.ok ? undefined : tail(a.ok ? b : a) };
});
step("ranking cases generated by the TypeScript ranker", () => {
  const r = sh(["bun", "s2-ranking-parity/gen.mts", join(data, "cases.jsonl")]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? lastJson(r.out) : tail(r) };
});
step("native ranking parity", () => {
  const r = sh([bin("parity", "s2-parity"), join(data, "cases.jsonl")]);
  if (!r.ok) return { ok: false, seconds: r.seconds, detail: tail(r) };
  const parsed = JSON.parse(r.out) as { rows: { variant: string; cases: number; id_or_order_mismatches: number; score_bit_mismatches: number; panics: number }[]; lowercase: { cases: number; mismatches: number; mismatches_touching_ascii: number } };
  const rows = parsed.rows.map((x) => ({ variant: x.variant, cases: x.cases, ids: x.id_or_order_mismatches, scores: x.score_bit_mismatches, panics: x.panics }));
  const exact = rows.filter((x) => !x.variant.startsWith("cosine/non-finite") && (x.variant.endsWith("f64 accumulator") || x.variant.endsWith("ascii-boundary scan") || x.variant.endsWith("(?-u:\\b)")));
  writeFileSync(join(data, "parity.json"), r.out);
  return { ok: exact.every((x) => x.ids === 0 && x.scores === 0), seconds: r.seconds, detail: { rows, lowercase: { cases: parsed.lowercase.cases, mismatches: parsed.lowercase.mismatches, touching_ascii: parsed.lowercase.mismatches_touching_ascii } } };
});
step("wasm module build", () => {
  const r = sh(["cargo", "build", "--release", "--locked", "-p", "bucket-rank-wasm-spike", "--target", "wasm32-unknown-unknown"]);
  if (r.ok) copyFileSync(join(spike, "target", "wasm32-unknown-unknown", "release", "bucket_rank_wasm_spike.wasm"), join(spike, "s3-wasm-in-bun", "rank.wasm"));
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? undefined : tail(r) };
});
step("bun build --compile with and without the wasm module", () => {
  const a = sh(["bun", "build", "--compile", "--minify", "s3-wasm-in-bun/app.mts", "--outfile", join(data, "app-wasm")]);
  const b = sh(["bun", "build", "--compile", "--minify", "s3-wasm-in-bun/baseline.mts", "--outfile", join(data, "app-ts")]);
  if (!a.ok || !b.ok) return { ok: false, seconds: a.seconds + b.seconds, detail: tail(a.ok ? b : a) };
  const s = sh(["bun", "s3-wasm-in-bun/sizes.mts", data]);
  return { ok: s.ok, seconds: a.seconds + b.seconds, detail: s.ok ? lastJson(s.out) : tail(s) };
});
step("wasm inside the compiled binary answers one search", () => {
  const r = sh([join(data, `app-wasm${exe}`), "search", "entropy light"]);
  const t = sh([join(data, `app-ts${exe}`), "search", "entropy light"]);
  const w = r.ok ? lastJson(r.out) : null;
  const j = t.ok ? lastJson(t.out) : null;
  return { ok: r.ok && t.ok && JSON.stringify(w.results) === JSON.stringify(j.results), seconds: r.seconds, detail: r.ok ? w : tail(r) };
});
step("wasm inside the compiled binary, every generated case", () => {
  const r = sh([join(data, `app-wasm${exe}`), "cases", join(data, "cases.jsonl")]);
  return { ok: r.ok, seconds: r.seconds, detail: lastJson(r.out) ?? tail(r) };
});
step("start time, compiled binary with wasm", () => {
  const r = sh(["bun", "bench.mts", "20", "3", "--", join(data, `app-wasm${exe}`), "search", "entropy light"]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? lastJson(r.out) : tail(r) };
});
step("start time, compiled binary with the TypeScript ranker", () => {
  const r = sh(["bun", "bench.mts", "20", "3", "--", join(data, `app-ts${exe}`), "search", "entropy light"]);
  return { ok: r.ok, seconds: r.seconds, detail: r.ok ? lastJson(r.out) : tail(r) };
});
step("sealed columns written by TypeScript, read by Rust", () => {
  const r = sh(["bun", "test", "./s6-sealed-reader/sealed.test.mts"], spike, { SEALED_DIR: join(data, "s6") });
  const file = join(data, "s6", "result.json");
  return { ok: r.ok, seconds: r.seconds, detail: existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : tail(r) };
});
step(`two writers for ${writerSeconds} seconds`, () => {
  const r = sh(["bun", "s1-two-writers/run.mts", writerSeconds, join(data, "s1"), bin("release", "s1-writer")]);
  const file = join(data, "s1", "result.json");
  if (!r.ok || !existsSync(file)) return { ok: false, seconds: r.seconds, detail: tail(r) };
  const d = JSON.parse(readFileSync(file, "utf8"));
  const writers = Object.values(d.writers) as { duplicated_rows: number; gaps: number; acked_missing: number; totals_match: boolean }[];
  const sound = d.bun_reader.integrity_check === "ok" && d.rust_reader.integrity_check === "ok" && writers.every((w) => w.duplicated_rows === 0 && w.gaps === 0 && w.acked_missing === 0 && w.totals_match);
  return { ok: sound, seconds: r.seconds, detail: d };
});

result.load = loadavg();
result.steps = steps;
writeFileSync(join(data, `result-${label}.json`), JSON.stringify(result, null, 2));
if (process.env.GITHUB_STEP_SUMMARY) {
  const rows = steps.map((s) => `| ${s.name} | ${s.ok ? "ok" : "FAIL"} | ${s.seconds} |`).join("\n");
  appendFileSync(process.env.GITHUB_STEP_SUMMARY, `### ${label}\n\n| Step | Result | Seconds |\n|---|---|---|\n${rows}\n`);
}
if (steps.some((s) => !s.ok)) process.exit(1);
